theme: jekyll-theme-cayman
show_downloads: true

github:
  zip_url: https://github.com/azureqaq/tjuptattendance/releases/latest/download/tjuptatt-x86_64-pc-windows-msvc.zip
  tar_url: https://github.com/azureqaq/tjuptattendance/releases/latest/download/tjuptatt-x86_64-unknown-linux-gnu.tar.gz
