# 实例配置文件, 展示高级设置

# 在此填写用户信息，可以指定多个
[[users]]
# 是否开启，如果关闭则不会对此用户进行签到
# 从命令行快速添加的默认是 true
enable = false
# 邮箱地址
# 用来发送邮件提醒
email = "asd@qq.com"
# 用户的登录名
id = "user_id"
# 用户的密码
pwd = "user_pwd"
# 重试次数
retry = 1

# 全局设置
[global]
# 网络延迟，如果用户设置中未指定，则会使用此值
# 范围 0~1000ms
retry = 3

# 邮件设置
# 用来发送邮件提醒
[global.emailconf]
# 是否开启邮件提醒
# 注意：就算开启了但是用户未填写邮箱，还是不会发送的
# 如果想要使用此功能，请提前进行测试
enable = false
# 登陆名
user = "登录名"
# 发件人，可以不指定
sender = "发件人"
# 登陆密码
pwd = "pwd"

# smtp设置，如果不指定则是 smtp.qq.com
host = "smtp.qq.com"
# 端口，如果不指定则是465
port = 465

